### ISSUE TITLE
Suggestion on Assignment 1

### ISSUE THREAD

**Issue by Meskerem3** [xulkif/assignment1#1]
Actually the code looks logically correct and run with out error but you don't full fill some of the requirement of the assignment  like you don't use switch case and you only use one of the arithmetic operation which is the addition in my point of view it will be better to use the switch case and the arithmetic together and in some part of the code it was sarcastic in the if statement part.

**Comment by Benawi** [comment]
Hi @xulkif       , @Meskerem3 
 Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Req implemented well 👨‍💻👩‍💻
- Java best practice not implemented well 👩‍💻👨‍💻
- Java best practice 
- Git flow  


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... Please change your code accordingly @Meskerem3   💪  to :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @benawi  in your question so I can receive the notification.

**Comment by xulkif** [comment]
I't is not mandatory to use switch because as we know that  we can use if
else statement instead of switch,both can be used as selection statement
interchangeably i prefer to use if else statement as you see ,i would  be
happy if you  consider this and review the code
